name: Pull Request Info

on:
  pull_request:
    branches:
      - main

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Print Hello World and PR info
      run: |
        echo "Hello World"
        echo "Autor: ${{ github.actor }}"
        echo "Último commit: "
        git log -1
        echo "Cambios entre el último commit y el default branch:"
        git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }}
